Neos:
  Neos:
    Ui:
      frontendConfiguration:
        Carbon.Editor.RelativeDate:
          timeSpans:
            minute: false
            hour: false
            day: true
            week: true
            month: true
            year: true
          allowFuture: true
          allowPast: true
